export * from './switch-form/switch-form.component';
export * from './pir-form/pir-form.component';
export * from './lux-form/lux-form.component';
export * from './band-settings/band-settings.component';
export * from './gpio-settings/gpio-settings.component';
export * from './hold-time-one/hold-time-one.component';
export * from './hold-time-two/hold-time-two.component';
export * from './hold-time-one-relay/hold-time-one-relay.component';
export * from './retransmissionp-settings/retransmissionp-settings.component';
